import type { GoalTemplate } from './types';

export const GOAL_TEMPLATES: GoalTemplate[] = [
        // Category I (600 hours)
        { id:'lang-afrikaans', title:'Learn Afrikaans', description:'Achieve conversational fluency in Afrikaans', hours:600, category:'Language', keywords:['afrikaans','language','learn','speak','fluent'] },
        { id:'lang-danish', title:'Learn Danish', description:'Achieve conversational fluency in Danish', hours:600, category:'Language', keywords:['danish','language','learn','speak','fluent'] },
        { id:'lang-dutch', title:'Learn Dutch', description:'Achieve conversational fluency in Dutch', hours:600, category:'Language', keywords:['dutch','language','learn','speak','fluent'] },
        { id:'lang-french', title:'Learn French', description:'Achieve conversational fluency in French', hours:600, category:'Language', keywords:['french','language','learn','speak','fluent'] },
        { id:'lang-italian', title:'Learn Italian', description:'Achieve conversational fluency in Italian', hours:600, category:'Language', keywords:['italian','language','learn','speak','fluent'] },
        { id:'lang-norwegian', title:'Learn Norwegian', description:'Achieve conversational fluency in Norwegian', hours:600, category:'Language', keywords:['norwegian','language','learn','speak','fluent'] },
        { id:'lang-portuguese', title:'Learn Portuguese', description:'Achieve conversational fluency in Portuguese', hours:600, category:'Language', keywords:['portuguese','language','learn','speak','fluent'] },
        { id:'lang-romanian', title:'Learn Romanian', description:'Achieve conversational fluency in Romanian', hours:600, category:'Language', keywords:['romanian','language','learn','speak','fluent'] },
        { id:'lang-spanish', title:'Learn Spanish', description:'Achieve conversational fluency in Spanish', hours:600, category:'Language', keywords:['spanish','language','learn','speak','fluent'] },
        { id:'lang-swedish', title:'Learn Swedish', description:'Achieve conversational fluency in Swedish', hours:600, category:'Language', keywords:['swedish','language','learn','speak','fluent'] },

        // Category II (750 hours)
        { id:'lang-german', title:'Learn German', description:'Achieve conversational fluency in German', hours:750, category:'Language', keywords:['german','language','learn','speak','fluent'] },

        // Category III (900 hours)
        { id:'lang-indonesian', title:'Learn Indonesian', description:'Achieve conversational fluency in Indonesian', hours:900, category:'Language', keywords:['indonesian','bahasa','language','learn','speak','fluent'] },
        { id:'lang-malaysian', title:'Learn Malaysian', description:'Achieve conversational fluency in Malaysian', hours:900, category:'Language', keywords:['malaysian','malay','language','learn','speak','fluent'] },
        { id:'lang-swahili', title:'Learn Swahili', description:'Achieve conversational fluency in Swahili', hours:900, category:'Language', keywords:['swahili','kiswahili','language','learn','speak','fluent'] },

        // Category IV (1100 hours)
        { id:'lang-albanian', title:'Learn Albanian', description:'Achieve conversational fluency in Albanian', hours:1100, category:'Language', keywords:['albanian','language','learn','speak','fluent'] },
        { id:'lang-amharic', title:'Learn Amharic', description:'Achieve conversational fluency in Amharic', hours:1100, category:'Language', keywords:['amharic','language','learn','speak','fluent'] },
        { id:'lang-armenian', title:'Learn Armenian', description:'Achieve conversational fluency in Armenian', hours:1100, category:'Language', keywords:['armenian','language','learn','speak','fluent'] },
        { id:'lang-azerbaijani', title:'Learn Azerbaijani', description:'Achieve conversational fluency in Azerbaijani', hours:1100, category:'Language', keywords:['azerbaijani','azerbaijan','language','learn','speak','fluent'] },
        { id:'lang-bengali', title:'Learn Bengali', description:'Achieve conversational fluency in Bengali', hours:1100, category:'Language', keywords:['bengali','bangla','language','learn','speak','fluent'] },
        { id:'lang-bosnian', title:'Learn Bosnian', description:'Achieve conversational fluency in Bosnian', hours:1100, category:'Language', keywords:['bosnian','language','learn','speak','fluent'] },
        { id:'lang-bulgarian', title:'Learn Bulgarian', description:'Achieve conversational fluency in Bulgarian', hours:1100, category:'Language', keywords:['bulgarian','language','learn','speak','fluent'] },
        { id:'lang-burmese', title:'Learn Burmese', description:'Achieve conversational fluency in Burmese', hours:1100, category:'Language', keywords:['burmese','myanmar','language','learn','speak','fluent'] },
        { id:'lang-croatian', title:'Learn Croatian', description:'Achieve conversational fluency in Croatian', hours:1100, category:'Language', keywords:['croatian','language','learn','speak','fluent'] },
        { id:'lang-czech', title:'Learn Czech', description:'Achieve conversational fluency in Czech', hours:1100, category:'Language', keywords:['czech','language','learn','speak','fluent'] },
        { id:'lang-estonian', title:'Learn Estonian', description:'Achieve conversational fluency in Estonian', hours:1100, category:'Language', keywords:['estonian','language','learn','speak','fluent'] },
        { id:'lang-finnish', title:'Learn Finnish', description:'Achieve conversational fluency in Finnish', hours:1100, category:'Language', keywords:['finnish','language','learn','speak','fluent'] },
        { id:'lang-georgian', title:'Learn Georgian', description:'Achieve conversational fluency in Georgian', hours:1100, category:'Language', keywords:['georgian','language','learn','speak','fluent'] },
        { id:'lang-greek', title:'Learn Greek', description:'Achieve conversational fluency in Greek', hours:1100, category:'Language', keywords:['greek','language','learn','speak','fluent'] },
        { id:'lang-hebrew', title:'Learn Hebrew', description:'Achieve conversational fluency in Hebrew', hours:1100, category:'Language', keywords:['hebrew','language','learn','speak','fluent'] },
        { id:'lang-hindi', title:'Learn Hindi', description:'Achieve conversational fluency in Hindi', hours:1100, category:'Language', keywords:['hindi','language','learn','speak','fluent'] },
        { id:'lang-hungarian', title:'Learn Hungarian', description:'Achieve conversational fluency in Hungarian', hours:1100, category:'Language', keywords:['hungarian','magyar','language','learn','speak','fluent'] },
        { id:'lang-icelandic', title:'Learn Icelandic', description:'Achieve conversational fluency in Icelandic', hours:1100, category:'Language', keywords:['icelandic','language','learn','speak','fluent'] },
        { id:'lang-khmer', title:'Learn Khmer', description:'Achieve conversational fluency in Khmer', hours:1100, category:'Language', keywords:['khmer','cambodian','language','learn','speak','fluent'] },
        { id:'lang-lao', title:'Learn Lao', description:'Achieve conversational fluency in Lao', hours:1100, category:'Language', keywords:['lao','language','learn','speak','fluent'] },
        { id:'lang-latvian', title:'Learn Latvian', description:'Achieve conversational fluency in Latvian', hours:1100, category:'Language', keywords:['latvian','language','learn','speak','fluent'] },
        { id:'lang-lithuanian', title:'Learn Lithuanian', description:'Achieve conversational fluency in Lithuanian', hours:1100, category:'Language', keywords:['lithuanian','language','learn','speak','fluent'] },
        { id:'lang-macedonian', title:'Learn Macedonian', description:'Achieve conversational fluency in Macedonian', hours:1100, category:'Language', keywords:['macedonian','language','learn','speak','fluent'] },
        { id:'lang-mongolian', title:'Learn Mongolian', description:'Achieve conversational fluency in Mongolian', hours:1100, category:'Language', keywords:['mongolian','language','learn','speak','fluent'] },
        { id:'lang-nepali', title:'Learn Nepali', description:'Achieve conversational fluency in Nepali', hours:1100, category:'Language', keywords:['nepali','language','learn','speak','fluent'] },
        { id:'lang-pashto', title:'Learn Pashto', description:'Achieve conversational fluency in Pashto', hours:1100, category:'Language', keywords:['pashto','language','learn','speak','fluent'] },
        { id:'lang-persian', title:'Learn Persian (Dari, Farsi, Tajik)', description:'Achieve conversational fluency in Persian', hours:1100, category:'Language', keywords:['persian','dari','farsi','tajik','language','learn','speak','fluent'] },
        { id:'lang-polish', title:'Learn Polish', description:'Achieve conversational fluency in Polish', hours:1100, category:'Language', keywords:['polish','language','learn','speak','fluent'] },
        { id:'lang-russian', title:'Learn Russian', description:'Achieve conversational fluency in Russian', hours:1100, category:'Language', keywords:['russian','language','learn','speak','fluent'] },
        { id:'lang-serbian', title:'Learn Serbian', description:'Achieve conversational fluency in Serbian', hours:1100, category:'Language', keywords:['serbian','language','learn','speak','fluent'] },
        { id:'lang-sinhala', title:'Learn Sinhala', description:'Achieve conversational fluency in Sinhala', hours:1100, category:'Language', keywords:['sinhala','sinhalese','language','learn','speak','fluent'] },
        { id:'lang-slovak', title:'Learn Slovak', description:'Achieve conversational fluency in Slovak', hours:1100, category:'Language', keywords:['slovak','language','learn','speak','fluent'] },
        { id:'lang-slovenian', title:'Learn Slovenian', description:'Achieve conversational fluency in Slovenian', hours:1100, category:'Language', keywords:['slovenian','language','learn','speak','fluent'] },
        { id:'lang-tagalog', title:'Learn Tagalog', description:'Achieve conversational fluency in Tagalog', hours:1100, category:'Language', keywords:['tagalog','filipino','language','learn','speak','fluent'] },
        { id:'lang-thai', title:'Learn Thai', description:'Achieve conversational fluency in Thai', hours:1100, category:'Language', keywords:['thai','language','learn','speak','fluent'] },
        { id:'lang-turkish', title:'Learn Turkish', description:'Achieve conversational fluency in Turkish', hours:1100, category:'Language', keywords:['turkish','language','learn','speak','fluent'] },
        { id:'lang-ukrainian', title:'Learn Ukrainian', description:'Achieve conversational fluency in Ukrainian', hours:1100, category:'Language', keywords:['ukrainian','language','learn','speak','fluent'] },
        { id:'lang-urdu', title:'Learn Urdu', description:'Achieve conversational fluency in Urdu', hours:1100, category:'Language', keywords:['urdu','language','learn','speak','fluent'] },
        { id:'lang-uzbek', title:'Learn Uzbek', description:'Achieve conversational fluency in Uzbek', hours:1100, category:'Language', keywords:['uzbek','language','learn','speak','fluent'] },
        { id:'lang-vietnamese', title:'Learn Vietnamese', description:'Achieve conversational fluency in Vietnamese', hours:1100, category:'Language', keywords:['vietnamese','language','learn','speak','fluent'] },
        { id:'lang-xhosa', title:'Learn Xhosa', description:'Achieve conversational fluency in Xhosa', hours:1100, category:'Language', keywords:['xhosa','language','learn','speak','fluent'] },
        { id:'lang-zulu', title:'Learn Zulu', description:'Achieve conversational fluency in Zulu', hours:1100, category:'Language', keywords:['zulu','language','learn','speak','fluent'] },

        // Category V (2200 hours)
        { id:'lang-arabic', title:'Learn Arabic', description:'Achieve conversational fluency in Arabic', hours:2200, category:'Language', keywords:['arabic','language','learn','speak','fluent'] },
        { id:'lang-cantonese', title:'Learn Cantonese (Chinese)', description:'Achieve conversational fluency in Cantonese', hours:2200, category:'Language', keywords:['cantonese','chinese','language','learn','speak','fluent'] },
        { id:'lang-mandarin', title:'Learn Mandarin (Chinese)', description:'Achieve conversational fluency in Mandarin Chinese', hours:2200, category:'Language', keywords:['mandarin','chinese','language','learn','speak','fluent'] },
        { id:'lang-japanese', title:'Learn Japanese', description:'Achieve conversational fluency in Japanese', hours:2200, category:'Language', keywords:['japanese','language','learn','speak','fluent'] },
        { id:'lang-korean', title:'Learn Korean', description:'Achieve conversational fluency in Korean', hours:2200, category:'Language', keywords:['korean','language','learn','speak','fluent'] },
        { id:'prog-react', title:'Master React Development', description:'Become proficient in React and modern frontend development', hours:200, category:'Programming', keywords:['react','javascript','frontend','web','development','programming'] },
        { id:'prog-python', title:'Learn Python Programming', description:'Master Python for data science and web development', hours:300, category:'Programming', keywords:['python','programming','data','science','web','development'] },
        { id:'prog-fullstack', title:'Full-Stack Web Development', description:'Learn complete web development stack', hours:500, category:'Programming', keywords:['fullstack','web','development','frontend','backend','programming'] },
        { id:'skill-piano', title:'Learn Piano', description:'Develop piano playing skills from beginner to intermediate', hours:500, category:'Music', keywords:['piano','music','instrument','play','learn'] },
        { id:'skill-guitar', title:'Learn Guitar', description:'Master acoustic guitar playing', hours:300, category:'Music', keywords:['guitar','music','instrument','play','learn','acoustic'] },
        { id:'skill-drawing', title:'Learn Drawing', description:'Develop artistic drawing and sketching skills', hours:200, category:'Art', keywords:['drawing','art','sketch','artistic','creative'] },
      ] as GoalTemplate[];
